# Generated by Django 4.2 on 2023-06-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshowss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, upload_to='tvshowss/images/'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
