# Generated by Django 4.2 on 2023-06-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshowss', '0002_reviews_image_reviews_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='date',
        ),
    ]
