# Generated by Django 4.2 on 2023-06-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='all',
            new_name='alls',
        ),
    ]
