# Generated by Django 4.2 on 2023-06-12 19:30

from django.db import migrations
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('all_reviews', '0002_rename_all_alls'),
    ]

    operations = [
        migrations.AddField(
            model_name='alls',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='alls',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
